# Generated by Django 3.1.7 on 2021-03-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(default=0),
        ),
    ]
